Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - "spec/**/*"
    - "node_modules/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "lib/**/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/puma.rb"
    - "config/application.rb"
